### ISSUE TITLE
how to make the "header" snippet work here?

### ISSUE THREAD

**Issue by weimindong2016** [Janfy/Sublime-Bash-Snippets#1]
Very nice piece. 

Just a minor question. How to make the "header" snippet work? I can make most of the other snippets work in my Sublime Text 3 (windows 10), except this "header" one. 

Thanks!

**Comment by Janfy** [comment]
Hi, 

Thanks you.

To use the "header", snippet, follow these steps:

* Create a new file: <kbd>ctrl</kbd> + <kbd>n</kbd>
* Set syntax to **Shell Script Bash**: <kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>p</kbd> + <kbd>sss</kbd>
* Then enter `#!`and press <kbd>tab</kbd>

![header-snippet](https://user-images.githubusercontent.com/717410/28480442-03cd52d8-6e61-11e7-9a12-141d1fadeb38.gif)

**Comment by weimindong2016** [comment]
thank you Janfy!  It works very well.
